function encode(s) {
   let b = 0;
   for(let t=0;t<s.length;t++) {
      
      if(s.charAt(t) != ".") {
         b |= 1<<t;
      }      
   }
   let msg = `00000000`+b.toString(2);   
   console.log(`   0b${msg.substr(msg.length-8)},`);
}

// char $0a.");
encode("........");
encode("........");
encode("........");
encode("........");
encode("........");
encode("........");
encode("........");
encode("........");
// char $0aX");
encode("...XXX..");
encode("...XXX..");
encode("...XXX..");
encode("...XX...");
encode("...XX...");
encode("........");
encode("...XX...");
encode("........");
// char $0a2");
encode("..XX.XX.");
encode("..XX.XX.");
encode("..X..X..");
encode("........");
encode("........");
encode("........");
encode("........");
encode("........");
// char $0a3");
encode("...X..XX");
encode("..XX..XX");
encode(".XXXXXX.");
encode("..XX.XX.");
encode("..XX.XXX");
encode(".XXXXXX.");
encode("..X..X..");
encode("........");
// char $0a4");
encode("..XXXX..");
encode(".XX.XXX.");
encode(".XX.X...");
encode("..XXXXX.");
encode("....X.XX");
encode(".XX.X.XX");
encode("..XXXXX.");
encode("........");
// char $0a5");
encode("..X....X");
encode(".X.X..X.");
encode("..X..X..");
encode("....X...");
encode("...X..X.");
encode("..X..X.X");
encode(".X....X.");
encode("........");
// char $0a6");
encode("...XX...");
encode("..X..X..");
encode("..XX.X..");
encode("..XXX...");
encode(".X..XX.X");
encode(".X...XX.");
encode("..XXX..X");
encode("........");
// char $0a7");
encode("..XX....");
encode("..XX....");
encode("...X....");
encode("..X.....");
encode("........");
encode("........");
encode("........");
encode("........");
// char $0a8");
encode(".....X..");
encode("....X...");
encode("...XX...");
encode("...X....");
encode("...XX...");
encode("....X...");
encode(".....X..");
encode("........");
// char $0a9");
encode("...X....");
encode("....X...");
encode("....XX..");
encode(".....X..");
encode("....XX..");
encode("....X...");
encode("...X....");
encode("........");
// char $0aa");
encode("........");
encode("...X..X.");
encode("....XX..");
encode("..XXXXXX");
encode("....XX..");
encode("...X..X.");
encode("........");
encode("........");
// char $0ab");
encode("........");
encode("....X...");
encode("....X...");
encode("..XXXXX.");
encode("....X...");
encode("....X...");
encode("........");
encode("........");
// char $0ac");
encode("........");
encode("........");
encode("........");
encode("........");
encode("...XX...");
encode("...XX...");
encode("..XX....");
encode("........");
// char $0ad");
encode("........");
encode("........");
encode("........");
encode("..XXXXX.");
encode("........");
encode("........");
encode("........");
encode("........");
// char $0ae");
encode("........");
encode("........");
encode("........");
encode("........");
encode("........");
encode("..XX....");
encode("..XX....");
encode("........");
// char $0af");
encode("........");
encode("......X.");
encode(".....X..");
encode("....X...");
encode("...X....");
encode("..X.....");
encode("........");
encode("........");
// char $0b.");
encode("...XXX..");
encode("..X..XX.");
encode(".XX...XX");
encode(".XX...XX");
encode(".XX...XX");
encode("..XX..X.");
encode("...XXX..");
encode("........");
// char $0bX");
encode("....XX..");
encode("...XXX..");
encode("....XX..");
encode("....XX..");
encode("....XX..");
encode("....XX..");
encode("..XXXXXX");
encode("........");
// char $0b2");
encode("..XXXXX.");
encode(".XX...XX");
encode(".....XXX");
encode("...XXXX.");
encode("..XXXX..");
encode(".XXX....");
encode(".XXXXXXX");
encode("........");
// char $0b3");
encode("..XXXXXX");
encode(".....XX.");
encode("....XX..");
encode("...XXXX.");
encode("......XX");
encode(".XX...XX");
encode("..XXXXX.");
encode("........");
// char $0b4");
encode("....XXX.");
encode("...XXXX.");
encode("..XX.XX.");
encode(".XX..XX.");
encode(".XXXXXXX");
encode(".....XX.");
encode(".....XX.");
encode("........");
// char $0b5");
encode(".XXXXXX.");
encode(".XX.....");
encode(".XXXXXX.");
encode("......XX");
encode("......XX");
encode(".XX...XX");
encode("..XXXXX.");
encode("........");
// char $0b6");
encode("...XXXX.");
encode("..XX....");
encode(".XX.....");
encode(".XXXXXX.");
encode(".XX...XX");
encode(".XX...XX");
encode("..XXXXX.");
encode("........");
// char $0b7");
encode(".XXXXXXX");
encode("......XX");
encode(".....XX.");
encode("....XX..");
encode("...XX...");
encode("...XX...");
encode("...XX...");
encode("........");
// char $0b8");
encode("..XXXX..");
encode(".XX...X.");
encode(".XXX..X.");
encode("..XXXX..");
encode(".X..XXXX");
encode(".X....XX");
encode("..XXXXX.");
encode("........");
// char $0b9");
encode("..XXXXX.");
encode(".XX...XX");
encode(".XX...XX");
encode("..XXXXXX");
encode("......XX");
encode(".....XX.");
encode("..XXXX..");
encode("........");
// char $0ba");
encode("........");
encode("...XX...");
encode("...XX...");
encode("........");
encode("...XX...");
encode("...XX...");
encode("........");
encode("........");
// char $0bb");
encode("........");
encode("...XX...");
encode("...XX...");
encode("........");
encode("...XX...");
encode("...XX...");
encode("..XX....");
encode("........");
// char $0bc");
encode(".....XX.");
encode("....XX..");
encode("...XX...");
encode("..XX....");
encode("...XX...");
encode("....XX..");
encode(".....XX.");
encode("........");
// char $0bd");
encode("........");
encode("........");
encode("..XXXXX.");
encode("........");
encode("..XXXXX.");
encode("........");
encode("........");
encode("........");
// char $0be");
encode("..XX....");
encode("...XX...");
encode("....XX..");
encode(".....XX.");
encode("....XX..");
encode("...XX...");
encode("..XX....");
encode("........");
// char $0bf");
encode("..XXXXX.");
encode(".XXXXXXX");
encode(".XX...XX");
encode(".....XX.");
encode("...XXX..");
encode("........");
encode("...XXX..");
encode("........");
// char $08.");
  encode("..XXXX..");
  encode(".X....X.");
  encode("X..XX..X");
  encode("X.X....X");
  encode("X.X....X");
  encode("X..XX..X");
  encode(".X....X.");
  encode("..XXXX..");
// char $08X");
  encode("...XXX..");
  encode("..XX.XX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XXXXXXX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode("........");
// char $082");
  encode(".XXXXXX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XXXXXX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XXXXXX.");
  encode("........");
// char $083");
  encode("...XXXX.");
  encode("..XX..XX");
  encode(".XX.....");
  encode(".XX.....");
  encode(".XX.....");
  encode("..XX..XX");
  encode("...XXXX.");
  encode("........");
// char $084");
  encode(".XXXXX..");
  encode(".XX..XX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX..XX.");
  encode(".XXXXX..");
  encode("........");
// char $085");
  encode(".XXXXXXX");
  encode(".XX.....");
  encode(".XX.....");
  encode(".XXXXXX.");
  encode(".XX.....");
  encode(".XX.....");
  encode(".XXXXXXX");
  encode("........");
// char $086");
  encode(".XXXXXXX");
  encode(".XX.....");
  encode(".XX.....");
  encode(".XXXXXX.");
  encode(".XX.....");
  encode(".XX.....");
  encode(".XX.....");
  encode("........");
// char $087");
  encode("...XXXXX");
  encode("..XX....");
  encode(".XX.....");
  encode(".XX..XXX");
  encode(".XX...XX");
  encode("..XX..XX");
  encode("...XXXXX");
  encode("........");
// char $088");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XXXXXXX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode("........");
// char $089");
  encode("..XXXXXX");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("..XXXXXX");
  encode("........");
// char $08a");
  encode("......XX");
  encode("......XX");
  encode("......XX");
  encode("......XX");
  encode("......XX");
  encode(".XX...XX");
  encode("..XXXXX.");
  encode("........");
// char $08b");
  encode(".XX...XX");
  encode(".XX..XX.");
  encode(".XX.XX..");
  encode(".XXXX...");
  encode(".XXXXX..");
  encode(".XX.XXX.");
  encode(".XX..XXX");
  encode("........");
// char $08c");
  encode("..XX....");
  encode("..XX....");
  encode("..XX....");
  encode("..XX....");
  encode("..XX....");
  encode("..XX....");
  encode("..XXXXXX");
  encode("........");
// char $08d");
  encode(".XX...XX");
  encode(".XXX.XXX");
  encode(".XXXXXXX");
  encode(".XX.X.XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode("........");
// char $08e");
  encode(".XX...XX");
  encode(".XXX..XX");
  encode(".XXXX.XX");
  encode(".XXXXXXX");
  encode(".XX.XXXX");
  encode(".XX..XXX");
  encode(".XX...XX");
  encode("........");
// char $08f");
  encode("..XXXXX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode("..XXXXX.");
  encode("........");
// char $09.");
  encode(".XXXXXX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XXXXXX.");
  encode(".XX.....");
  encode(".XX.....");
  encode("........");
// char $09X");
  encode("..XXXXX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX.XXXX");
  encode(".XX..XX.");
  encode("..XXXX.X");
  encode("........");
// char $092");
  encode(".XXXXXX.");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX..XXX");
  encode(".XXXXX..");
  encode(".XX.XXX.");
  encode(".XX..XXX");
  encode("........");
// char $093");
  encode("..XXXX..");
  encode(".XX..XX.");
  encode(".XX.....");
  encode("..XXXXX.");
  encode("......XX");
  encode(".XX...XX");
  encode("..XXXXX.");
  encode("........");
// char $094");
  encode("..XXXXXX");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("........");
// char $095");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode("..XXXXX.");
  encode("........");
// char $096");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XXX.XXX");
  encode("..XXXXX.");
  encode("...XXX..");
  encode("....X...");
  encode("........");
// char $097");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX...XX");
  encode(".XX.X.XX");
  encode(".XXXXXXX");
  encode(".XXX.XXX");
  encode(".XX...XX");
  encode("........");
// char $098");
  encode(".XX...XX");
  encode(".XXX.XXX");
  encode("..XXXXX.");
  encode("...XXX..");
  encode("..XXXXX.");
  encode(".XXX.XXX");
  encode(".XX...XX");
  encode("........");
// char $099");
  encode("..XX..XX");
  encode("..XX..XX");
  encode("..XX..XX");
  encode("...XXXX.");
  encode("....XX..");
  encode("....XX..");
  encode("....XX..");
  encode("........");
// char $09a");
  encode(".XXXXXXX");
  encode(".....XXX");
  encode("....XXX.");
  encode("...XXX..");
  encode("..XXX...");
  encode(".XXX....");
  encode(".XXXXXXX");
  encode("........");
// char $09b");
  encode("...XXXX.");
  encode("...XX...");
  encode("...XX...");
  encode("...XX...");
  encode("...XX...");
  encode("...XX...");
  encode("...XXXX.");
  encode("........");
// char $09c");
  encode("........");
  encode("........");
  encode("........");
  encode("........");
  encode("........");
  encode("........");
  encode("........");
  encode("........");
// char $09d");
  encode("...XXXX.");
  encode(".....XX.");
  encode(".....XX.");
  encode(".....XX.");
  encode(".....XX.");
  encode(".....XX.");
  encode("...XXXX.");
  encode("........");
// char $09e");
  encode("........");
  encode("...XX...");
  encode("..XXXX..");
  encode(".XXXXXX.");
  encode("...XX...");
  encode("...XX...");
  encode("...XX...");
  encode("...XX...");
// char $09f");
  encode("........");
  encode("...X....");
  encode("..XX....");
  encode(".XXXXXXX");
  encode(".XXXXXXX");
  encode("..XX....");
  encode("...X....");
  encode("........");
